name: weekday_selector
description: A collection of Flutter widgets and classes to help you select weekdays in your apps. Perfect for recurring events, alarms.
version: 0.1.0
author: Vince Varga <vince.varga@smaho.com>
homepage: https://github.com/smaho-engineering/weekday_selector
repository: https://github.com/smaho-engineering/weekday_selector
issue_tracker: https://github.com/smaho-engineering/weekday_selector/issues
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
